<?php
USE u174025152_EIR;

CREATE TABLE IF NOT EXISTS vehiculo (
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    Buque VARCHAR(25) NOT NULL,
    Viaje VARCHAR(25) NOT NULL,
    VIN VARCHAR(50) NOT NULL UNIQUE,
    Marca VARCHAR(20) NOT NULL,
    Modelo VARCHAR(15) NOT NULL,
    Color VARCHAR(20),
    Año VARCHAR(10),
    Puerto VARCHAR(30),
    Terminal VARCHAR(20)
);
?>