-- Crear base de datos
CREATE DATABASE IF NOT EXISTS EIR CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE EIR;

-- Tabla vehículo
CREATE TABLE IF NOT EXISTS vehiculo (
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    Buque VARCHAR(25) NOT NULL,
    Viaje VARCHAR(25) NOT NULL,
    VIN VARCHAR(50) NOT NULL UNIQUE,
    Marca VARCHAR(20) NOT NULL,
    Modelo VARCHAR(15) NOT NULL,
    Color VARCHAR(20),
    Año VARCHAR(10),
    Puerto VARCHAR(30),
    Terminal VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
