-- Agregar campo ID autoincremental y PRIMARY KEY a las tablas base
ALTER TABLE areadano ADD COLUMN ID INT AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE tipodano ADD COLUMN ID INT AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE severidaddano ADD COLUMN ID INT AUTO_INCREMENT PRIMARY KEY FIRST;

-- Asegurar que VIN en vehiculo sea PRIMARY KEY o UNIQUE y tipo VARCHAR(50)
ALTER TABLE vehiculo MODIFY COLUMN VIN VARCHAR(50) NOT NULL;
ALTER TABLE vehiculo ADD UNIQUE (VIN);

-- Crear la tabla RegistroDanio correctamente
CREATE TABLE IF NOT EXISTS RegistroDanio (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VIN VARCHAR(50) NOT NULL,
    AreaID INT NOT NULL,
    TipoID INT NOT NULL,
    SeveridadID INT NOT NULL,
    FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VIN) REFERENCES vehiculo(VIN),
    FOREIGN KEY (AreaID) REFERENCES areadano(ID),
    FOREIGN KEY (TipoID) REFERENCES tipodano(ID),
    FOREIGN KEY (SeveridadID) REFERENCES severidaddano(ID)
) ENGINE=InnoDB;
