<?php
// Conexión a la base de datos en Hostinger
$servername = "localhost";
$username = "u174025152_Administrador";
$password = "0066jv_A2";
$dbname = "u174025152_EIR";

// Crear conexión
$conn = new mysqli($servername, $username, $password, $dbname);

// Verificar conexión
if ($conn->connect_error) {
    die("Conexión fallida: " . $conn->connect_error);
}

// Crear tabla área de daño
$sql = "CREATE TABLE IF NOT EXISTS areadano (
    CodAreaDano INT(10) PRIMARY KEY AUTO_INCREMENT,
    NomAreaDano VARCHAR(100) NOT NULL
)";

if ($conn->query($sql) === TRUE) {
    echo "Tabla 'areadano' creada exitosamente";
    
    // Insertar datos iniciales
    $insertData = "INSERT INTO areadano (NomAreaDano) VALUES
    ('ANTENA/ANTENA BASE'),
    ('BATERÍA'),
    ('PARACHOQUES/CUBIERTA/EXTERIOR-DELANTERO'),
    ('PARACHOQUES/CUBIERTA/EXTERIOR-TRASERO'),
    ('PROTECTOR DE PARACHOQUES/STRIP-DELANTERO'),
    ('PARACHOQUES PROTECTOR/STRIP-REAR'),
    ('PUERTA TRASERA DE CARGA-DERECHA'),
    ('PUERTA TRASERA DE CARGA–IZQUIERDA'),
    ('PUERTA CORREDIZA IZQUIERDA/DERECHA TRASERA'),
    ('PUERTA-FRENTE IZQUIERDO'),
    ('PUERTA-TRASERA IZQUIERDA'),
    ('PUERTA-FRENTE DERECHO'),
    ('PUERTA-DERECHA TRASERA'),
    ('SALPICADERA-DELANTERO IZQUIERDO'),
    ('OTR PANEL/PICK UP CAJA-IZQUIERDA'),
    ('SALPICADERA-DELANTERO DERECHO'),
    ('OTR PANEL/PICK UP CAJA-DERECHA'),
    ('ALFOMBRAS DE PISO-DELANTERO'),
    ('ALFOMBRAS DE PISO-TRASERAS'),
    ('PARABRISA'),
    ('VIDRIO-TRASERO'),
    ('REJILLA'),
    ('ACELERADOR/PEDAL-TRANSMISION DEL VEHICULO/O-BOLSA/CAJA'),
    ('FARO/TAPA/SEÑAL DE ORO'),
    ('LAMPARAS-NIEBLA/CONDUCCION/LUZ PUNTUAL'),
    ('FORRO O COBERTOR INTERIOR DE TECHO'),
    ('CAPO'),
    ('LLAVES'),
    ('CONTROL REMOTO SIN LLAVE'),
    ('ESPEJO-EXTERIOR IZQUIERDO'),
    ('ESPEJO-EXTERIOR DERECHO'),
    ('DAÑO MAYOR/ (Paro uso del OEM)'),
    ('REPRODUCTOR MULTIMEDIA FRONTAL'),
    ('REPRODUCTOR MULTIMEDIA TRASERO'),
    ('ROCKER PANEL/SOLERA EXTERIOR-IZQUIERDA'),
    ('ROCKER PANEL/SOLERA EXTERIOR-RIGHT'),
    ('TECHO'),
    ('CARRERA-PASO A LA IZQUIERDA'),
    ('TABLERO DE CORREIR/PASO-DERECHO'),
    ('NEUMÁTICO DE REPUESTO'),
    ('Cable para cargar vehículo eléctrico'),
    ('PANEL SPLASH/SPOILER-DELANTERO'),
    ('ABIERTO'),
    ('TANQUE DE GASOLINA'),
    ('LUZ DE COLA/HARDWARE'),
    ('CABINA DE CAMION, TRASERA'),
    ('ABIERTO'),
    ('PANEL DE CUBIERTA DE PUERTA-DELANTERO IZQUIERDO'),
    ('ABIERTO'),
    ('PANEL DE CUBIERTA DE PUERTA-DELANTERO DERECHO'),
    ('TUNJEAU'),
    ('TAPA DE LA CUBIERTA/PORTÓN TRASERO/HATCHBACK'),
    ('TECHO CORREDIZO/TECHO SOLAR'),
    ('ÁREA DEBAJO DEL VEHÍCULO'),
    ('ÁREA DE CARGA-OTROS'),
    ('CONVERTIBLE SUPERIOR'),
    ('TAPAS/GORRAS DE RUEDAS'),
    ('ALTAVOCES DE RADIO'),
    ('LIMPIAPARBRISAS-TODOS'),
    ('CHOCKS SALTADO'),
    ('CAJA DE RECOGIDA-INTERIOR'),
    ('TODO EL VEHÍCULO'),
    ('REJEC-CUBIERTA DE CAMA DEL CAMION/BARRA DE LUZ'),
    ('SPOILER/DEFLECTOR-TRASERO'),
    ('PORTAEQUIPAJES (TIRAS)/RIEL DE GOTEO'),
    ('DASH/PANEL DE INSTRUMENTOS'),
    ('ENCENDEDOR DE CIGARRILLOS/BANDEJA DE CENICERA'),
    ('ALFOMBRA - DELANTERO'),
    ('ABIERTO'),
    ('POSTE CENTRAL -IZQUIERDA'),
    ('POSTE DE ESQUINA'),
    ('NEUMÁTICO DELANTERO IZQUIERDO'),
    ('RIM/RUEDA DELANTERA IZQUIERDA'),
    ('NEUMÁTICO TRASERO IZQUIERDO'),
    ('RIM/RUEDA TRASERA IZQUIERDA'),
    ('NEUMÁTICO TRASERO DERECHO'),
    ('RIM/RUEDA TRASERA DERECHA'),
    ('NEUMÁTICO DELANTERO DERECHO'),
    ('RIM/RUEDA DELANTERA DERECHA'),
    ('CONVERTIBLE ENTRE EL HOOD Y CRISTAL DELANTERO.'),
    ('PUERTA/TAPA DE GASOLINA/PUERTA DE CARGA DE BATERÍA'),
    ('SALPICADERA-TRASERA IZQUIERDA'),
    ('SALPICADERA-TRASERA DERECHA'),
    ('HERRAMIENTAS /ACK JUEGO PARA Cambio de llantas & LOCK'),
    ('KIT DE TARJETA MULTIMEDIA'),
    ('SENSORES/SISTEMA SONAR DE PARQUEO'),
    ('ABIERTO'),
    ('ABIERTO'),
    ('ENGANCHE DE REMOLQUE/ARNÉS DE CABLEADO/GANCHOS DE REMOLQUE'),
    ('MARCO'),
    ('TUBO DE ESCAPE'),
    ('SOPORTE DE PLACA DE MATRÍCULA DEL VEHÍCULO'),
    ('VOLANTE/AIRBAG'),
    ('ASIENTO-DELANTERO IZQUIERDO'),
    ('ASIENTO-DELANTERO DERECHO'),
    ('ASIENTO-TRASERO'),
    ('ALFOMBRA-TRASERO'),
    ('INTERIOR'),
    ('COMPARTIMIENTO DEL MOTOR-OTROS')";
    
    if ($conn->query($insertData) === TRUE) {
        echo " y datos insertados exitosamente";
    } else {
        echo " pero error al insertar datos: " . $conn->error;
    }
} else {
    echo "Error al crear tabla: " . $conn->error;
}

$conn->close();
?>
